/** Тексты интерфейса — отдельным слоем от разметки.
 *
 *  Компоненты не держат ни одной строки: подписи, кнопки, подсказки и сообщения живут здесь,
 *  по разделу на файл компонента (S.home, S.ruleEditor, ...). Поправить формулировку —
 *  значит поправить её здесь, не открывая вёрстку; второй язык — второй такой же файл с тем же
 *  типом (см. copy/index.ts).
 *
 *  Строки с числами и именами — функциями: склонение и порядок слов решает текст, а не
 *  компонент. Порядок разделов — по алфавиту файлов. */
/** Число со словом в нужной форме: 1 подписка, 3 подписки, 5 подписок, 21 подписка.
 *  Прежде формы выбирались прямо в разметке по «1 / 2–4 / остальное», и выходило «21 подписок». */
const plural = (n: number, one: string, few: string, many: string) => {
    const m10 = n % 10, m100 = n % 100
    const w = m10 === 1 && m100 !== 11 ? one : m10 >= 2 && m10 <= 4 && (m100 < 12 || m100 > 14) ? few : many
    return `${n} ${w}`
}

export const ru = {
    /** Кнопки диалога подтверждения. Были английскими («Cancel», «Confirm»): t() не переводила
     *  ничего, и в русском интерфейсе стояли английские слова. */
    confirm: {
        cancel: "Отмена",
        confirm: "Подтвердить",
    },
    applyPill: {
        izmeneniyaUzheSohranenyKnopka: "Изменения уже сохранены. Кнопка отправит их в ядро — около двух секунд, соединения не рвутся.",
        primeneno: " Применено",
        primenyaem: " Применяем…",
        primenit: " Применить",
    },
    backupCard: {
        neUdalosSobratArhiv: "не удалось собрать архив",
        arhivPrislanNePolnostyu: "архив прислан не полностью",
        arhivSlishkomVelikDlya: "архив слишком велик для чтения по кускам",
        arhivNastroekSohranenKb: (p0: unknown) => `Архив настроек сохранён: ${p0} КБ`,
        vosstanovitNastroykiIzFayla: "Восстановить настройки из файла?",
        pravilaVyhodyPodpiskaI: "Правила, выходы, подписка и свои списки будут заменены на те, что в файле. ",
        primenenieOstanetsyaZaVami: "Применение останется за вами: восстановленное появится как неприменённое.",
        vosstanovit: "Восстановить",
        faylPust: "файл пуст",
        faylNePrinyat: "файл не принят",
        nastroykiVosstanovleny: "Настройки восстановлены:",
        pravilaIVyhody: "правила и выходы,",
        podpiska: "подписка,",
        svoiSpiski: (p0: unknown) => `свои списки (${p0}),`,
        otbroshenoStrok: (p0: unknown) => `отброшено строк: ${p0},`,
        primenitKnopkoyPrimenit: "применить — кнопкой «Применить».",
        bekapNastroek: "Бекап настроек",
        odinFaylPravilaVyhody: "Один файл: правила, выходы, подписка и свои списки. Списки каталога не входят — роутер скачает их сам.",
        vFayleEstSsylki: "В файле есть ссылки vless:// с ключами. Храните его как пароль.",
        skachatArhiv: "Скачать архив",
        faylSNastroykami: "Файл с настройками",
        vosstanovlenieNichegoNePrimenyaet: "Восстановление ничего не применяет: файл проверяется, настройки сохраняются, маршрутизация меняется только после «Применить».",
    },
    catalogTab: {
        spisokNash: "список наш",
        spisokVneshniy: "список внешний",
        neHvataetDomenaPredlozhite: (p0: unknown) => `Не хватает домена — предложите его в наш список${p0}. Правки прямо на роутере исчезнут при обновлении.`,
        dobavitDomenMozhnoU: (p0: unknown) => `Добавить домен можно у апстрима${p0} или своим списком. Правки прямо на роутере исчезнут при обновлении.`,
        domeny: (p0: unknown) => `домены — ${p0}`,
        predlozhitDomen: "предложить домен",
        pustoyKatalog: "пустой каталог",
        neObnovilosChasteyIz: (p0: unknown, p1: unknown, p2: unknown) => `${p0}: не обновилось частей — ${p1} из ${p2}`,
        obnovleno: (p0: unknown, p1: unknown) => `${p0}: обновлено${p1}`,
        neObnovilosSpiskov: (p0: unknown) => `Не обновилось списков: ${p0}`,
        obnovlenoSpiskov: (p0: unknown) => `Обновлено списков: ${p0}`,
        spiskiUzheSvezhie: "Списки уже свежие",
        obnovitSpiskiNeUdalos: "Обновить списки не удалось",
        neUdalosUdalitChastey: (p0: unknown, p1: unknown, p2: unknown) => `${p0}: не удалось удалить (частей ${p1} из ${p2})`,
        udalenSRoutera: (p0: unknown) => `${p0}: удалён с роутера`,
        katalogNeZagruzilsyaProverte: "Каталог не загрузился. Проверьте адрес источника («Настройки → Источник списков») и доступ роутера в интернет.",
        poiskPoKatalogu: "поиск по каталогу",
        chtoPokazyvat: "Что показывать",
        vse: (p0: unknown) => `все · ${p0}`,
        ispolzuyutsya: (p0: unknown) => `используются · ${p0}`,
        obnovitSpiski: "Обновить списки",
        svoySpisok: " Свой список",
        zapis: "Запись",
        zapisey: "Записей",
        gdeIspolzuetsya: "Где используется",
        domenyIAdresa: "домены и адреса",
        tolkoDomeny: "только домены",
        tolkoAdresa: "только адреса",
        chastey: (p0: unknown) => ` · частей ${p0}`,
        prichina: (p0: unknown) => `Причина: ${p0}. `,
        etoOdnaITa: "Это одна и та же группа адресов, вошедшая в запись двумя файлами: второй не добавляет ни одного адреса.",
        vklyuchatObeZapisiOdnovremenno: "Включать обе записи одновременно бессмысленно: вторая не добавляет ни одного адреса, а расход памяти удваивается.",
        odinSpisokAdresov: (p0: unknown) => `один список адресов: «${p0}»`,
        totZheSpisokAdresov: (p0: unknown) => `тот же список адресов, что у «${p0}»`,
        etaZapisDopolnyaetA: (p0: unknown) => `Эта запись дополняет «${p0}», а не заменяет её: в ней только домены, которых там нет. Включать имеет смысл обе — по отдельности каждая неполна.`,
        ryadomEstNashSpisok: (p0: unknown) => `Рядом есть наш список «${p0}»: он дополняет эту запись, а не заменяет её — в нём домены, которых здесь нет. Включать имеет смысл обе, иначе добавленный домен в туннель не попадёт.`,
        dopolnyaetVklyuchayteOba: (p0: unknown) => `дополняет «${p0}» — включайте оба`,
        ryadomNashSpisokVklyuchayte: (p0: unknown) => `рядом наш список «${p0}» — включайте оба`,
        zapisey2: "записей",
        zagruzhen: "загружен",
        neZagruzhen: "не загружен",
        vPravilo: "В правило",
        spiskaEscheNetNa: "Списка ещё нет на роутере. Как только правило на него укажет и вы нажмёте «Применить», роутер скачает его сам.",
        skachaetsyaSam: "скачается сам",
        spiskiObnovlyayutsyaSamiRaz: "Списки обновляются сами раз в сутки по расписанию. Кнопка — если свежая версия нужна прямо сейчас.",
        obnovit: (p0: unknown) => `Обновить ${p0}`,
        udalitSRoutera: (p0: unknown) => `Удалить ${p0} с роутера`,
        nichegoNeNashlos: "Ничего не нашлось.",
        ispolzuyutsyaPravilamiNoKatalog: "Используются правилами, но каталог их больше не предлагает",
        etiSpiskiOstalisOt: "Эти списки остались от прежнего каталога — источник сменился или издатель убрал запись. Правила с ними работают, но обновляться они больше не будут, и выбрать такой список заново отсюда нельзя. Снять — на вкладке правил.",
        katalogIstochnikaSkachatNe: "Каталог источника скачать не вышло — показана таблица из пакета:",
        versiyaZafiksirovanaTegom: ", версия зафиксирована тегом",
        pereopredelenNastroykoy: " (переопределён настройкой)",
        katalogSpravkaZapisNachinaet: "Каталог — справка: запись начинает работать, когда на неё укажет правило. Нужные списки скачиваются и обновляются сами. Источник каталога — в «Настройки → Источник списков»",
        versiya: (p0: unknown) => `, версия ${p0}`,
    },
    clientNetsCard: {
        cherezEtotInterfeysRouter: "через этот интерфейс роутер уходит наружу, а не принимает клиентов",
        etoUstroystvoVashegoVyhoda: "это устройство вашего выхода: через него трафик уходит наружу, а не приходит от клиентов",
        interfeysVedetNaruzhuOttuda: "интерфейс ведёт наружу: оттуда приходит не ваша сеть, а весь мир по ту сторону роутера",
        dolzhnoOstatsyaHotyaBy: "Должно остаться хотя бы одно устройство — иначе ядру некому адресовать правила.",
        seychasKlientovZadayutPodseti: "Сейчас клиентов задают подсети. Второе устройство рядом с ними ядро отвергнет.",
        kogoMarshrutiziruem: "Кого маршрутизируем",
        pravilaKasayutsyaUstroystvKotorye: "Правила касаются устройств, которые приходят через эти интерфейсы — например, из Tailscale или ZeroTier, если роутер им шлюз.",
        seychasKlientovZadayutPodseti2: "Сейчас клиентов задают подсети (",
        iVyborUstroystvNe: "), и выбор устройств не действует.",
        zadavatKlientovUstroystvami: "Задавать клиентов устройствами",
        seychasNaRoutereNet: "сейчас на роутере нет",
        adresaPokaNet: "адреса пока нет",
        naruzhu: "наружу",
        ustroystvNeNashlosEsli: "Устройств не нашлось. Если splify2 только что обновился — откройте страницу заново.",
        yadroEtoyVersiiPerechnya: "Ядро этой версии перечня устройств не понимает и заберёт трафик только с br-lan. Обновите ядро в разделе «Настройки» — иначе выбор здесь ничего не изменит.",
        ustroystvoKotorogoSeychasNet: "Устройство, которого сейчас нет, выбрать можно: правило заработает само, когда оно поднимется.",
        adresPokazanChtobyVy: "Адрес показан, чтобы вы узнали, какое устройство какое. Правилам он не нужен.",
        vybranoToChtoIstochnikom: "Выбрано то, что источником трафика быть не может: ",
        trafikVashihUstroystvOttuda: ". Трафик ваших устройств оттуда не придёт, и правила на них не встанут.",
    },
    console: {
        zagruzka: "Загрузка…",
        sohraneno: " Сохранено",
    },
    customLists: {
        ssylka: (p0: unknown) => `ссылка ${p0}`,
        ssylka2: "ссылка",
        fayl: (p0: unknown) => `файл ${p0}`,
        fayl2: "файл",
        zapisiVruchnuyu: "записи вручную",
        spisokStrokOtbroshenoFormat: (p0: unknown, p1: unknown, p2: unknown) => `Список «${p0}»: строк ${p1}, отброшено ${p2} — формат не подошёл`,
        spisokStrok: (p0: unknown, p1: unknown) => `Список «${p0}»: строк ${p1}`,
        neSkachalos: "не скачалось",
        neSohranilos: "не сохранилось",
        imyaSpiskaLatinitsaTsifry: "Имя списка: латиница, цифры, дефис и подчёркивание",
        spisokPust: "Список пуст",
        ssylkaDolzhnaNachinatsyaS: "Ссылка должна начинаться с http:// или https://",
        neUdalosUdalit: "не удалось удалить",
        spisokUdalen: (p0: unknown) => `Список «${p0}» удалён`,
        svoiSpiski: "Свои списки",
        spiskov: (p0: unknown) => `списков: ${p0}`,
        domenyIPodsetiKotoryh: "Домены и подсети, которых нет у издателя. После добавления список появится в редакторе правил рядом с остальными — сам по себе он ничего не меняет.",
        domeny: "домены",
        podseti: "подсети",
        zapisey: " · записей ",
        izmenitSpisok: (p0: unknown) => `Изменить список ${p0}`,
        udalitSpisok: (p0: unknown) => `Удалить список ${p0}`,
        imyaSpiska: "имя списка",
        imyaSpiska2: "Имя списка",
        vidSpiska: "Вид списка",
        tolkoLatinitsaTsifryDefis: "только латиница, цифры, дефис и подчёркивание",
        zapisiSpiska: "Записи списка",
        poOdnomuImeniNa: "по одному имени на строку:\nexample.org\nsub.example.net",
        poOdnoyPodsetiNa: "по одной подсети на строку:\n10.0.0.0/8\n192.0.2.1",
        sohranit: "Сохранить",
        faylSoSpiskom: "Файл со списком",
        httpsSkachaetRouter: "https://… — скачает роутер",
        ssylkaNaSpisok: "Ссылка на список",
        skachat: "Скачать",
        skachivaetsyaOdinRazObnovlyat: "Скачивается один раз. Обновлять придётся этой же кнопкой: расписание есть только у списков издателя.",
        neProchitalos: "не прочиталось",
        seychasIzFaylaVyberite: (p0: unknown) => `Сейчас из файла ${p0}. Выберите другой файл — он заменит список целиком.`,
        vyberiteFaylOnZamenit: "Выберите файл — он заменит список целиком.",
        drugoyFaylDlyaSpiska: (p0: unknown) => `Другой файл для списка ${p0}`,
        ssylkaOtkudaRouterBeret: "Ссылка, откуда роутер берёт этот список. Скачивается по нажатию: расписания у своего списка нет.",
        ssylkaSpiska: (p0: unknown) => `Ссылка списка ${p0}`,
        skachatZanovo: "Скачать заново",
        spisokSlishkomVelikChtoby: "Список слишком велик, чтобы править его текстом (",
        kbZameniteEgoFaylom: " КБ). Замените его файлом или ссылкой.",
        zapisiNeProchitalis: "Записи не прочитались: ",
        pravitTekstomSeychasNelzya: ". Править текстом сейчас нельзя — замените список файлом или ссылкой.",
        chitaemZapisi: "Читаем записи…",
        zapisiSpiskaSohranenieZamenyaet: "Записи списка. Сохранение заменяет его целиком.",
        zapisiSpiska2: (p0: unknown) => `Записи списка ${p0}`,
        sohranitZapisi: "Сохранить записи",
    },
    diagnostics: {
        proverkaSostoyaniyaNedostupna: "Проверка состояния недоступна",
        proverokSOtkazom: (p0: unknown) => `проверок с отказом: ${p0}`,
        proverokSPreduprezhdeniem: (p0: unknown) => `проверок с предупреждением: ${p0}`,
        vseVPoryadke: "Всё в порядке",
        obnoviteSteerVRazdele: "Обновите steer в разделе «Настройки → О ПО».",
        logiSteer: "Логи steer",
        obnovit: "Обновить",
        poiskPoZhurnalu: "Поиск по журналу…",
        ochistitPoisk: "Очистить поиск",
        zagruzkaZhurnala: "Загрузка журнала…",
        strokPoZaprosu: "Строк по запросу «",
        neNaydeno: "» не найдено.",
        sbrositFiltr: "Сбросить фильтр",
        yadroNichegoNePisalo: "Ядро ничего не писало в журнал.",
    },
    /** Выход с устройством, которое не отвечает (lib/outstate.ts). */
    outState: {
        neOtvechaet: "не отвечает",
        uzelNeOtvechaet: "узел не отвечает",
        vyhodNeOtvechaet: "Выход не отвечает",
        uzelNeOtvechaetT: "Узел не отвечает",
        trafikOstanovlen: "Трафик этого выхода остановлен, пока выход не ответит.",
        trafikNapryamuyu: "Трафик этого выхода идёт напрямую, пока выход не ответит.",
        trafikCherezObhod: "Трафик этого выхода идёт через обход, пока выход не ответит.",
        vernyotsyaSam: "Выход вернётся сам, когда узел ответит.",
        mostTelegram: "мост Telegram",
        putiNeOtvechayut: (n: number) => `не отвечает путей: ${n}`,
        sertifikatNeProveryaetsya: "сертификат не проверяется",
        ipv6ZdesNeDeystvuet: "IPv6 от хоста здесь не действует",
        ipv6Prefiks: (p: unknown) => `IPv6 ${p}`,
        ipv6PrefiksNeIzvesten: "префикс IPv6 не определён",
        ipv6AdresomHosta: "IPv6 адресом хоста",
        ipv6NePodmenyaetsya: "IPv6 не подменяется",
    },
    dns: {
        rabotaet: "работает",
        zhdetVoprosov: "ждёт вопросов",
        soedinyaetsya: "соединяется",
        neOtvechaet: "не отвечает",
        vyhodNeRazmechen: "выход не размечен",
        nuzhnaSborkaSTls: "нужна сборка с TLS",
        dnsPoTcp: "DNS по TCP",
        zagruzka: "Загрузка…",
        serverVybranVPravilah: (p0: unknown, p1: unknown) => `Сервер «${p0}» выбран в правилах: ${p1}`,
        serveryDns: "Серверы DNS",
        serverov: (p0: unknown) => `серверов: ${p0}`,
        serverovNetImenaPod: "Серверов нет: имена под правилами спрашиваются у системного DNS роутера.",
        imyaServera: (p0: unknown) => `имя сервера ${p0}`,
        otvetov: (p0: unknown) => ` · ответов: ${p0}`,
        ubrat: (p0: unknown) => `убрать ${p0}`,
        adres: "Адрес",
        cherezVyhod: "Через выход",
        napryamuyu: "напрямую",
        adresaServera: "Адреса сервера",
        dobavit: "Добавить",
        dobavit2: " Добавить",
        svoyAdres: "Свой адрес",
        kakSprashivat: "Как спрашивать",
        serverPoUmolchaniyuDlya: "Сервер по умолчанию для имён под правилами",
        sistemnyyDnsRoutera: "системный DNS роутера",
        serveryDlyaRazresheniyaImen: "Серверы для разрешения имён серверов (обычный DNS)",
        rezhimDomennyhPravil: "Режим доменных правил",
        poddelnyeAdresa: "Поддельные адреса",
        nastoyaschieAdresa: "Настоящие адреса",
        tochneePoDomenamZnachenie: "точнее по доменам, значение по умолчанию",
        trassirovkaViditNastoyaschieUzly: "трассировка видит настоящие узлы",
        zapiseyVKesheOtvetov: "Записей в кэше ответов",
        n0BezKesha: "0 — без кэша",
        kesh: "кэш",
        vKesheIzPopadaniy: (p0: unknown, p1: unknown, p2: unknown, p3: unknown) => `в кэше ${p0} из ${p1} · попаданий ${p2}, промахов ${p3}`,
        razreshatImyaCherez: "Разрешать имя через (обычный DNS)",
        poUmolchaniyuObschie: "общие серверы ниже",
        hranitNeMenshe: "Хранить ответ не меньше, с",
        hranitNeDolshe: "Хранить ответ не дольше, с",
        otritsatelnyyOtvetHranit: "Ответ «нет такого имени» хранить, с",
        minBolsheMax: "«Не меньше» больше, чем «не дольше» — ядро такие настройки не примет.",
        http: (p0: unknown) => ` · ${p0 === 'h2' ? 'HTTP/2' : 'HTTP/1.1'}`,
        early: (p0: unknown, p1: unknown) => ` · 0-RTT: ${p0}${p1 ? `, отвергнуто ${p1}` : ''}`,
    },
    engine: {
        ustanovit: "Установить",
        pereustanovit: "Переустановить",
        obnovitDo: (p0: unknown) => `Обновить до ${p0}`,
    },
    engineCard: {
        vyberiteVersiyu: "Выберите версию",
        neUstanovilos: "не установилось",
        paketUstanovlen: "Пакет установлен",
        yadroPriEtomNe: "Ядро при этом не запустилось — маршрутизации сейчас нет. Посмотрите журнал.",
        yadroUstanovleno: "Ядро установлено",
        yadroNeUstanovleno: "Ядро не установлено",
        yadroUstarelo: "Ядро устарело",
        ustanovlenoBazovoeYadro: "Установлено базовое ядро",
        yadro: "Ядро",
        versiya: "версия",
        variant: "вариант",
        rasshirennyy: "расширенный",
        bazovyy: "базовый",
        arhitektura: "архитектура",
        bezNegoMarshrutizirovatNechem: "Без него маршрутизировать нечем: ни одно правило не заработает.",
        arhitekturaPaketov: "Архитектура пакетов",
        etotInterfeysSobranPod: "Этот интерфейс собран под ядро",
        iNoveeSUstanovlennym: "и новее. С установленным настройки не применятся. Обновите ядро — версии ниже.",
        bazovyyUmeetVseKrome: "Базовый умеет всё, кроме одного: поднимать туннель VLESS сам. Для подписки нужен расширенный.",
        rasshirennyy2: "Расширенный",
        podnimaetTunnelSamVstavili: "Поднимает туннель сам: вставили ссылку подписки — и всё. Занимает на флеше ~500 КБ.",
        bazovyy2: "Базовый",
        tolkoMarshrutizatsiyaTunnelPodnimaete: "Только маршрутизация. Туннель поднимаете вы: wireguard, amneziawg — что уже работает. Занимает на флеше ~250 КБ, вдвое меньше расширенного.",
        versiyaYadra: "Версия ядра",
        zagruzka: "загрузка…",
        relizovNeNaydeno: "релизов не найдено",
        svezhaya: "свежая",
        spisokVersiyNePrishel: "Список версий не пришёл — проверьте интернет на роутере. Можно поставить пакет вручную:",
        gitlabComXyzmeanSteer: "gitlab.com/xyzmean/steer (ветка dist)",
    },
    engineToggle: {
        ostanovitVse: "Остановить всё?",
        marshrutizatsiyaSnimetsyaTselikomYadro: "Маршрутизация снимется целиком: ядро steer остановится, правила из ядра Linux уйдут. ",
        avtozapuskTozheSnimetsyaPoetomu: "Автозапуск тоже снимется, поэтому перезагрузка роутера ничего не вернёт — ",
        vklyuchatPridetsyaEtoyZhe: "включать придётся этой же кнопкой.",
        ostanovit: "Остановить",
        yadroOstanovleno: "Ядро остановлено",
        yadroZapuscheno: "Ядро запущено",
        yadroVklyuchenoNoNe: "Ядро включено, но не поднялось",
        yadro: "ядро",
        yadraNet: "Ядра нет",
        primenitNastroykuNechem: "применить настройку нечем",
        sekundu: "Секунду…",
        zapustit: "Запустить",
        ostanovitVse2: "Остановить всё",
        avtozapuskSnyatPerezagruzkaYadro: "автозапуск снят: перезагрузка ядро не вернёт",
        yadroRabotaetHotyaAvtozapusk: "ядро работает, хотя автозапуск снят — остановите ещё раз, если оно не нужно",
    },
    fetchCard: {
        neSohranilos: "не сохранилось",
        sohraneno: "Сохранено",
        skachivanie: "Скачивание",
        skachivatSpiskiIObnovleniya: "Скачивать списки и обновления через туннель",
        poydetCherezVyhod: "пойдёт через выход",
        podnyatogoVyhodaSeychasNet: "поднятого выхода сейчас нет",
    },
    firstRun: {
        yadroNeUstanovleno: "Ядро не установлено",
        marshrutizatsieyZanimaetsya: "Маршрутизацией занимается ",
        pokaEgoNetProveryat: ". Пока его нет, проверять и применять нечего — начните отсюда.",
        podnimaetVlessRealitySam: "— поднимает VLESS/Reality сам, достаточно подписки. Нужен, если туннеля на роутере ещё нет.",
        tolkoMarshrutizatsiyaPoGotovym: "— только маршрутизация по готовым устройствам: wireguard, amneziawg, любой существующий интерфейс.",
        paketMozhnoPostavitI: "Пакет можно поставить и руками:",
        naRoutereS64: ". На роутере с 64 МБ памяти перед установкой остановите ядро, если оно работает: иначе обновлению может не хватить памяти.",
    },
    format: {
        s: " с",
        min: " мин",
        ch: " ч",
        bS: "Б/с",
        kbS: "КБ/с",
        mbS: "МБ/с",
        gbS: "ГБ/с",
        b: "Б",
        kb: "КБ",
        mb: "МБ",
        gb: "ГБ",
        tb: "ТБ",
        tolkoChto: "только что",
        sNazad: " с назад",
        minNazad: " мин назад",
        chNazad: " ч назад",
        nikogda: "никогда",
    },
    geo: {
        armeniya: "Армения",
        avstriya: "Австрия",
        azerbaydzhan: "Азербайджан",
        belgiya: "Бельгия",
        bolgariya: "Болгария",
        braziliya: "Бразилия",
        kanada: "Канада",
        shveytsariya: "Швейцария",
        kipr: "Кипр",
        chehiya: "Чехия",
        germaniya: "Германия",
        daniya: "Дания",
        estoniya: "Эстония",
        ispaniya: "Испания",
        finlyandiya: "Финляндия",
        frantsiya: "Франция",
        velikobritaniya: "Великобритания",
        gruziya: "Грузия",
        gonkong: "Гонконг",
        vengriya: "Венгрия",
        irlandiya: "Ирландия",
        izrail: "Израиль",
        indiya: "Индия",
        italiya: "Италия",
        yaponiya: "Япония",
        kazahstan: "Казахстан",
        litva: "Литва",
        lyuksemburg: "Люксембург",
        latviya: "Латвия",
        moldaviya: "Молдавия",
        niderlandy: "Нидерланды",
        norvegiya: "Норвегия",
        polsha: "Польша",
        portugaliya: "Португалия",
        rumyniya: "Румыния",
        serbiya: "Сербия",
        rossiya: "Россия",
        shvetsiya: "Швеция",
        singapur: "Сингапур",
        slovakiya: "Словакия",
        turtsiya: "Турция",
        ukraina: "Украина",
        ssha: "США",
        oae: "ОАЭ",
        avstraliya: "Австралия",
    },
    groupEditor: {
        pervyyZhivoy: "Первый живой",
        poPoryadkuVernetsyaNa: "по порядку; вернётся на верхний, когда он оживёт",
        samyyBystryy: "Самый быстрый",
        poZameruZaderzhki: "по замеру задержки",
        vyborVruchnuyu: "Выбор вручную",
        chlenVybiraeteVyBez: "член выбираете вы, без применения",
        porovnuPoVesam: "Поровну по весам",
        novyeSoedineniyaRazdayutsyaPo: "новые соединения раздаются по живым членам",
        imyaLatinitsaTsifryDefis: "Имя: латиница, цифры, дефис или подчёркивание",
        vyhodUzheEst: (p0: unknown) => `Выход «${p0}» уже есть`,
        vyberiteHotyaByOdin: "Выберите хотя бы один выход",
        vyhodZanyatPravilami: (p0: unknown, p1: unknown) => `Выход «${p0}» занят правилами: ${p1}`,
        vyhodVhoditVGruppy: (p0: unknown, p1: unknown) => `Выход «${p0}» входит в группы: ${p1}`,
        nePoluchilos: "не получилось",
        vybran: (p0: unknown) => `Выбран ${p0}`,
        dobavitGruppu: "Добавить группу",
        otmena: "Отмена",
        sohranitGruppu: " Сохранить группу",
        imyaGruppy: "имя группы",
        esliVseChlenyUpali: "Если все члены упали",
        kakVybirat: "Как выбирать",
        dopuskMs: "Допуск, мс",
        zamerRazVS: "Замер раз в, с",
        adresProverki: "Адрес проверки",
        neMeritBezTrafika: "Не мерить без трафика дольше, с",
        n0MeritVsegda: "0 — мерить всегда",
        nePropuskatIpv6: "Не пропускать IPv6",
        chleny: "Члены",
        drugihVyhodovPokaNet: "Других выходов пока нет — сначала заведите их.",
        nesetTrafik: "несёт трафик",
        zhiv: "жив",
        neOtvechaet: "не отвечает",
        ms: (p0: unknown) => ` · ${p0} мс`,
        ves: (p0: unknown) => `вес ${p0}`,
        poUmolchaniyu: "по умолчанию",
        vybrat: "Выбрать",
        vyshe: "выше",
        nizhe: "ниже",
        vybran2: "Выбран: ",
        udalit: " Удалить",
    },
    home: {
        yadroNeOtvechaet: "Ядро не отвечает",
        estPolomki: "Есть поломки",
        proverokSOtkazom: (p0: unknown) => `проверок с отказом: ${p0}`,
        marshrutizatsiyaRabotaet: "Маршрутизация работает",
        proverokSPreduprezhdeniem: (p0: unknown) => `проверок с предупреждением: ${p0}`,
        zagruzka: "Загрузка…",
        sovetov: (p0: unknown) => `советов: ${p0}`,
        primenyaetsya: "Применяется…",
        zapuskaetsya: "Запускается…",
        obnovlenie: "Обновление…",
        s: (p0: unknown) => `${p0} с`,
        dCh: (p0: unknown, p1: unknown) => `${p0} д ${p1} ч`,
        chMin: (p0: unknown, p1: unknown) => `${p0} ч ${p1} мин`,
        min: (p0: unknown) => `${p0} мин`,
        yadroNeChitaetNovuyu: "Ядро устарело",
        etotInterfeysZapisyvaetNastroyki: "Изменения не применятся. Обновите ядро: Настройки → О ПО.",
        ustroystvVSeti: "устройств в сети: ",
        vremyaRaboty: " · время работы ",
        diagnostika: "диагностика ",
        sovet: "совет: ",
        trafikuNekudaIdti: " Трафику некуда идти",
        vyhodovNetNiOdin: "Выходов нет: ни один туннель не заведён, поэтому правилам некуда вести трафик — он идёт напрямую, как будто ничего не настроено. Выход создаётся в разделе",
        aSamoTunnelnoeUstroystvo: ", а само туннельное устройство — в настройках сети роутера.",
        vyhod: "Выход ",
        nePodnyatUstroystvoEmu: " не поднят: устройство ему не назначено, маршрутизировать нечем.",
        nePodnyat: " не поднят:",
        ustroystv: "устройств",
        ustroystva: "устройства",
        netVSistemeTunnel: " нет в системе. Туннель создаётся в настройках сети роутера — пока устройства нет, трафик этого выхода не уходит никуда.",
        preduprezhdeniyaSteer: " Предупреждения steer",
        dobavitPravilo: " Добавить правило",
        pravila: "Правила",
        sZagruzkiRoutera: "с загрузки роутера",
        pravilNetVesTrafik: "Правил нет — весь трафик идёт напрямую.",
        podpiska: "подписка",
        zapas: (p0: unknown) => `запас: ${p0}`,
        esliVseUpalo: (p0: unknown) => `если всё упало: ${p0}`,
        vyklyucheno: "выключено",
        netVYadreLinux: "нет в ядре Linux",
        napryamuyu: "напрямую",
        ms: (p0: unknown) => `${p0} мс`,
        chlenyNeOtvechayut: "члены не отвечают",
        nePodnyat2: "не поднят",
        obschiySchetchik: (p0: unknown) => `общий счётчик: ${p0}`,
        schetchikObschiy: "счётчик общий",
        vyhody: "Выходы",
        meryaem: "меряем…",
        proverit: "проверить",
        neUstanovlenCurlStrana: "Не установлен curl: страна и отклик выходов не измеряются. Установите пакет curl.",
        vPule: (p0: unknown) => `в пуле ${p0}`,
        kudaPoydetZapros: "Куда пойдёт запрос",
        youtubeComKudaPoydet: "youtube.com — куда пойдёт трафик?",
        ochistit: "Очистить",
        sprashivaem: "Спрашиваем…",
        proverit2: "Проверить",
        primery: "Примеры:",
    },
    ifacesPanel: {
        zagruzka: "Загрузка…",
        vyhodZanyatPravilami: (p0: unknown, p1: unknown) => `Выход «${p0}» занят правилами: ${p1}`,
        tunnelnyhUstroystvNetTunnel: "Туннельных устройств нет. Туннель создаётся в настройках сети роутера.",
        vVyhodah: (p0: unknown) => `в выходах: ${p0}`,
    },
    layout: {
        nazad: "Назад",
    },
    listsSourceCard: {
        neSohranilos: "не сохранилось",
        istochnikSpiskovIzmenen: "Источник списков изменён",
        vernulsyaSvoyKatalogSpiskov: "Вернулся свой каталог списков",
        istochnikSpiskov: "Источник списков",
        ssylkaKatalogaSpiskov: "ссылка каталога списков",
        minutu: "минуту…",
        sohranit: "Сохранить",
        vernutSvoy: "Вернуть свой",
        katalogEtoPerechenSpiskov: "Каталог — это перечень списков: какие бывают, как называются и где лежит каждый. Уже скачанные списки и правила смена источника не трогает.",
        seychasKatalogSplify2: "Сейчас — каталог splify2.",
    },
    live: {
        n0B: "0 Б",
        b: "Б",
        kb: "КБ",
        mb: "МБ",
        gb: "ГБ",
        tb: "ТБ",
        mbitS: (p0: unknown) => `${p0} Мбит/с`,
        kbitS: (p0: unknown) => `${p0} кбит/с`,
        bitS: (p0: unknown) => `${p0} бит/с`,
        routerVernulOshibku: "роутер вернул ошибку",
    },
    model: {
        ostanovitTrafik: "остановить трафик",
        pustitNapryamuyu: "пустить напрямую",
        napryamuyuCherezZapret: "напрямую через zapret",
        porty: (p0: unknown, p1: unknown) => `${p0} (порты ${p1})`,
        porty2: (p0: unknown) => `${p0} (порты)`,
        svoySpisokDomenov: "свой список доменов",
        svoySpisokPodsetey: "свой список подсетей",
    },
    obfsPanel: {
        wireguardPoverhTcp: "WireGuard поверх TCP",
        obfuskatsiyaVklyuchena: "обфускация включена",
        pryachetTunnelVPotok: "Прячет туннель в поток, похожий на обычный TCP. Нужно там, где UDP режут: маршрутизация выглядит исправной, а туннель не поднимается. На другой стороне должен работать ",
        iliPhantun: " или phantun.",
        serverObfuskatsii: "Сервер обфускации",
        adresServeraObfuskatsii: "Адрес сервера обфускации",
        port: "Порт",
        portServeraObfuskatsii: "Порт сервера обфускации",
        lokalnyyPortEndpointPira: "Локальный порт (= Endpoint пира)",
        lokalnyyPortObfuskatora: "Локальный порт обфускатора",
        bezAdresaServeraObfuskatsii: "Без адреса сервера обфускации выход не сохранится.",
        nuzhenAdresANe: "Нужен адрес, а не имя.",
        portChisloOt1: "Порт — число от 1 до 65535.",
        vNastroykahPiraWireguard: "В настройках пира WireGuard ",
        dolzhenUkazyvatNa: " должен указывать на",
        inacheTrafikUydetMimo: " — иначе трафик уйдёт мимо обфускатора и туннель молча не поднимется. И MTU: поверх TCP конверт на 12 байт больше, чем поверх UDP, поэтому у интерфейса туннеля обычно ",
        vmesto1440OdinakovoS: " вместо 1440, одинаково с обеих сторон.",
    },
    outputAdvanced: {
        dopolnitelno: "Дополнительно",
        tunnelIdetCherezVyhod: "Туннель идёт через выход",
        napryamuyu: "напрямую",
        transportUzlov: "Транспорт узлов",
        lyuboy: "любой",
        ipv6OtHosta: "IPv6 от хоста",
        poUmolchaniyu: "по умолчанию",
        prefiksHosta: "префикс хоста",
        odinAdresHosta: "один адрес хоста",
        nePropuskatIpv6: "не пропускать IPv6",
        prefiks: "Префикс",
        n2001Db8156: "2001:db8:1::/56 — пусто: определить по сети",
        kakVybiratIzSpiska: "Как выбирать из списка",
        pervyyZhivoy: "первый живой",
        samyyBystryy: "самый быстрый",
        dopuskMs: "Допуск, мс",
        zamerRazVS: "Замер раз в, с",
        adresProverki: "Адрес проверки",
        neMeritBezTrafika: "Не мерить без трафика дольше, с",
        n0MeritVsegda: "0 — мерить всегда",
    },
    outputCards: {
        netOtveta: "нет ответа",
        ms: (p0: unknown) => `${p0} мс`,
        panelNeOtvetila: "панель не ответила",
        panelNeSoobschilaOstatok: "панель не сообщила остаток",
        podpiska: "Подписка",
        obnovleno: "обновлено ",
        sprashivaem: "спрашиваем…",
        obnovit: "обновить",
        iz: "из ",
        ostalos: " осталось",
        izrashodovano: "израсходовано ",
        sbros: "сброс ",
        doKontsaPerioda: "до конца периода",
        vSrednemVSutki: "в среднем в сутки",
        hvatitPriTakomTempe: "хватит при таком темпе",
        doKontsaPeriodaS: "до конца периода с запасом",
        na: (p0: unknown) => `на ${p0}`,
        priNyneshnemTempeTrafik: "При нынешнем темпе трафик кончится раньше сброса. Когда он кончится, узел перестанет подниматься: выход упадёт, а правила останутся на месте — трафик пойдёт туда, куда велит",
        esliVseUpalo: "если всё упало",
        uEtogoVyhoda: " у этого выхода.",
        obemNeOgranichen: "объём не ограничен",
        poSchetuPaneli: "по счёту панели",
        sbros2: (p0: unknown) => `сброс ${p0}`,
        panelNeSoobschaetOstatok: "Панель не сообщает остаток",
        bezLimita: "без лимита",
        izIzrashodovano: "из ∞ израсходовано",
        bezOgranicheniya: "без ограничения",
        vneshniyAdres: "внешний адрес",
        skrytVneshniyAdres: "скрыть внешний адрес",
        pokazatVneshniyAdres: "показать внешний адрес",
        podklyuchaetsya: "Подключается…",
        proveryaemUzlyPodpiskiIz: (p0: unknown, p1: unknown) => `проверяем узлы подписки: ${p0} из ${p1}`,
        podnimaemVyhod: (p0: unknown) => `поднимаем выход ${p0}`,
        uzlaNetVPodpiske: "Узла нет в подписке",
        vybranUzelAPrigodnyh: (p0: unknown, p1: unknown) => `выбран узел ${p0}, а пригодных в подписке ${p1}`,
        vybrannogoUzlaVPodpiske: "выбранного узла в подписке нет",
        podpiskaObnovilasIUzlov: ". Подписка обновилась и узлов стало меньше — выберите локацию заново или поставьте «первый рабочий».",
        netSoedineniya: "Нет соединения",
        vPodpiskeNetPrigodnyh: "в подписке нет пригодных узлов",
        niOdinUzelPodpiski: "ни один узел подписки не ответил",
        vyhodNePodnyatUstroystva: (p0: unknown) => `выход ${p0} не поднят: устройства нет`,
        pokaEgoNetTrafik: ". Пока его нет, трафик этого выхода никуда не идёт.",
    },
    pending: {
        neUdalosSohranit: "не удалось сохранить",
        primeneno: "Применено",
        sboyPrimeneniya: "сбой применения",
    },
    poolEditor: {
        pickedCount: (n: number) => ` · взято: ${n}`,
        pickedAny: " · взята любая",
        yadroEtoyVersiiNe: "Ядро этой версии не умеет смешанный пул: либо одна подписка, либо свои туннели. Обновите ядро в разделе «Настройки → О ПО».",
        imyaLatinitsaTsifryDefis: "Имя: латиница, цифры, дефис или подчёркивание",
        vyhodUzheEst: (p0: unknown) => `Выход «${p0}» уже есть`,
        vyberiteCherezChtoVyhodit: "Выберите, через что выходить",
        imyaVyhodaPodpiskiNe: (p0: unknown) => `Имя выхода подписки — не длиннее ${p0} символов: оно становится именем устройства`,
        vyhodZanyatPravilami: (p0: unknown, p1: unknown) => `Выход «${p0}» занят правилами: ${p1}`,
        zakryt: "Закрыть",
        sohranitVyhod: " Сохранить выход",
        obhodDpi: "Обход DPI",
        ustroystvaUEtogoVyhoda: "Устройства у этого выхода нет: трафик идёт обычным маршрутом через обход DPI. Стратегия настраивается вне splify2.",
        esliObhodNeRabotaet: "Если обход не работает",
        udalit: " Удалить",
        dobavitVyhod: "Добавить выход",
        otmena: "Отмена",
        chtoMozhnoVzyat: "Что можно взять",
        naytiLokatsiyuStranaIli: "найти локацию: страна или слово из названия",
        naytiLokatsiyu: "найти локацию",
        ochistitPoisk: "очистить поиск",
        podpiski: "Подписки",
        podpisokNetDobavteV: "подписок нет — добавьте в подпункте VLESS",
        neSkachana: "не скачана",
        lokatsiy: (p0: unknown, p1: unknown) => `локаций: ${p0}${p1}`,
        ostanovitOstalos: (p0: unknown) => `остановить (осталось ${p0})`,
        proveritVse: (p0: unknown) => `проверить все${p0}`,
        lyubayaRabochaya: "любая рабочая",
        neSlomaetsyaPriObnovlenii: "не сломается при обновлении подписки",
        uzlovNetDlyaSsylok: "Узлов нет: для ссылок hysteria2 не установлен пакет steer-hysteria2.",
        vPodpiskeEscheUzlov: (p0: unknown) => `В подписке ещё ${p0} узлов hysteria2: нужен пакет steer-hysteria2.`,
        uzlovNetYadroNe: "Узлов нет: ядро не приняло ссылки этой подписки.",
        yadroNePrinyaloEsche: (p0: unknown) => `Ядро не приняло ещё ${p0} ссылок этой подписки.`,
        lyubayaRabochayaHysteria2: "любая рабочая (hysteria2)",
        uzlyChitayutsya: "узлы читаются…",
        lokatsiiPoyavyatsyaPoslePrimenit: "локации появятся после «Применить»",
        nichegoNeNashlos: "ничего не нашлось",
        uzel: (p0: unknown) => `узел ${p0}`,
        vOcheredi: "в очереди",
        proveryayu: "проверяю…",
        neProverilsya: "не проверился",
        ms: " мс",
        neOtvechaet: "не отвечает",
        proveritOtklik: "проверить отклик",
        proveritOtklik2: (p0: unknown) => `проверить отклик: ${p0}`,
        pokazatVseLokatsiy: (p0: unknown) => `показать все ${p0} локаций`,
        svernut: "свернуть",
        svoiTunneli: "Свои туннели",
        tunnelnyhUstroystvNet: "туннельных устройств нет",
        zanyatoDrugimVyhodom: "занято другим выходом",
        vyhod: (p0: unknown) => `выход ${p0}`,
        imyaVyhoda: "имя выхода",
        esliVseUpalo: "Если всё упало",
        poryadokPredpochteniya: "Порядок предпочтения",
        nichegoNeVybranoOtmette: "ничего не выбрано — отметьте локации или туннели в списке «Что можно взять»",
        poryadokPredpochteniya2: "порядок предпочтения",
        strokaVyshe: (p0: unknown) => `строка ${p0} выше`,
        strokaNizhe: (p0: unknown) => `строка ${p0} ниже`,
        ubratStroku: (p0: unknown) => `убрать строку ${p0}`,
        pervayaZhivayaStrokaZabiraet: "Первая живая строка забирает трафик; когда верхняя оживает, трафик возвращается к ней сам.",
        strokiMozhnoTaschitMyshyu: "Строки можно тащить мышью или переставлять стрелками, локации разных подписок — в любом порядке.",
        mezhduSosednimiLokatsiyamiOdnoy: "Между соседними локациями одной подписки трафик переходит за секунды, между остальными строками — до минуты.",
    },
    poolList: {
        pervyyZhivoy: "первый живой",
        samyyBystryy: "самый быстрый",
        vyborVruchnuyu: "выбор вручную",
        poVesam: "по весам",
        podpiska: "подписка",
        zagruzka: "Загрузка…",
        dobavitGruppu: " Добавить группу",
        dobavitVyhod: " Добавить выход",
        vyhody: "Выходы",
        vyhodovNet: "Выходов нет",
        dobavteVyhodSvoyTunnel: "Добавьте выход (свой туннель или подписку), чтобы правила могли направлять через него трафик.",
        nuzhenPaketSteer: (p0: unknown) => `нужен пакет steer-${p0}`,
        napryamuyuMimoTunnelya: "напрямую, мимо туннеля",
        obhodDpi: "обход DPI",
        pravil: (p0: unknown) => `правил: ${p0}`,
        seychas: (p0: unknown) => `сейчас: ${p0}`,
        chlenyNeOtvechayut: "члены не отвечают",
        chlenov: (p0: unknown) => `членов: ${p0}`,
        ustroystvoNeVybrano: "устройство не выбрано",
        ms: (p0: unknown) => `${p0} мс`,
    },
    quota: {
        tolkoChto: "только что",
        minNazad: (p0: unknown) => `${p0} мин назад`,
        chNazad: (p0: unknown) => `${p0} ч назад`,
        dNazad: (p0: unknown) => `${p0} д назад`,
        dney: (p0: unknown) => `${p0} дней`,
        den: (p0: unknown) => `${p0} день`,
        dnya: (p0: unknown) => `${p0} дня`,
    },
    rail: {
        glavnaya: "Главная",
        pravila: "Правила",
        diagnostika: "Диагностика",
        nastroyki: "Настройки",
        razdely: "Разделы",
    },
    rpc: {
        netOtveta: "нет ответа",
    },
    ruleEditor: {
        praviloIz: (p0: unknown, p1: unknown) => `Правило ${p0} из ${p1}`,
        vsePravila: "Все правила",
        nazvaniePravila: "Название правила",
        kogoKasaetsya: "Кого касается",
        vseUstroystvaVSeti: "Все устройства в сети",
        tolkoVybrannye: "Только выбранные",
        n192168150: "192.168.1.50, 192.168.1.0/24, fd00::/64 или MAC",
        macVidenTolkoU: "MAC виден только у устройств своей сети: за вторым роутером правило накроет всех, кто за ним.",
        neAdresINe: "Не адрес и не MAC: ",
        takuyuZapisYadroVybrosit: " — с такой записью ядро не примет настройки. Исправьте или уберите её.",
        chtoPerenapravlyaem: "Что перенаправляем",
        zapiseyVybrano: (p0: unknown) => `${p0} записей выбрано`,
        nichegoNeVybrano: "ничего не выбрано",
        servisov: (p0: unknown) => `сервисов ${p0}`,
        servisNeVybran: "сервис не выбран",
        zapisey: (p0: unknown) => ` · ${p0} записей`,
        poiskPoKataloguServisy: "поиск по каталогу — сервисы, категории",
        zapisey2: " записей",
        nichegoNeNashlos: "Ничего не нашлось.",
        skachivaetsya: "скачивается",
        skachaetsya: "скачается",
        domenyIAdresa: "домены и адреса",
        domeny: "домены",
        adresa: "адреса",
        vPravileEstFayly: "В правиле есть файлы не из каталога",
        ubrat: "убрать",
        oniProdolzhayutRabotatI: "Они продолжают работать и обновляться. Каталог их больше не предлагает, поэтому выбрать такой файл заново отсюда будет нельзя.",
        vybiraetsyaServisEsliU: "Выбирается сервис: если у него есть и домены, и адреса, в правило попадут оба. Домены точнее, адреса работают и когда устройство не спрашивает DNS роутера.",
        kudaNapravlenieVyhod: "Куда — направление (выход)",
        vyhodovNetPraviluNekuda: "Выходов нет — правилу некуда вести. Подключение настраивается во вкладке «VPN».",
        tunnel: "Туннель ",
        podnyatNoNePrivyazan: " поднят, но не привязан к выходу — во вкладке «VPN».",
        napryamuyu: "Напрямую",
        mimoTunnelya: "мимо туннеля",
        netNat: "нет NAT",
        podpiska: "подписка",
        etoIsklyuchenieVybrannoePoydet: "Это исключение: выбранное пойдёт мимо туннеля. Работает, пока правило стоит выше туннельных. Сейчас оно ",
        eIz: "-е из ",
        isklyucheniePerekrytoVysheStoit: "Исключение перекрыто: выше стоит «",
        sTemiZheZapisyami: "» с теми же записями — трафик заберёт оно, и исключение не сработает. Поднимите его стрелкой ↑ в списке правил.",
        rezhimDomenov: "Режим доменов",
        fakeIpTochnee: "fake-IP — точнее",
        realIpDeshevle: "real-IP — дешевле",
        fakeIpKazhdomuDomenu: "fake-IP: каждому домену свой адрес — точно, но дороже по памяти. real-IP: настоящие адреса из ответа — дешевле, но два домена за одним адресом станут одним.",
        serverDns: "Сервер DNS",
        poUmolchaniyu: "по умолчанию",
        svoyAdresDns: "свой адрес",
        adresDns: "Адрес сервера DNS",
        dnsCherezVyhod: "Запрос через выход",
        dnsNapryamuyu: "напрямую",
        dnsAdresaServera: "IP сервера DNS",
        portNaznacheniya: "Порт назначения",
        portKakUZaprosa: "как у запроса",
        portOt1Do65535: "Порт — от 1 до 65535",
        gotovo: "Готово",
        udalitPravilo: " Удалить правило",
    },
    rulesTab: {
        vesTrafik: "весь трафик",
        servisNeVybran: "сервис не выбран",
        svoiSpiski: (p0: unknown) => `свои списки: ${p0}`,
        iEsche: (p0: unknown, p1: unknown) => `${p0} и ещё ${p1}`,
        zapisey: (p0: unknown, p1: unknown) => `${p0} · ${p1} записей`,
        vsehUstroystv: "всех устройств",
        adresovIPodsetey: (p0: unknown) => `адресов и подсетей: ${p0}`,
        pustoyKatalog: "пустой каталог",
        snachalaNastroyteVyhodVpn: "Сначала настройте выход VPN — правилу некуда вести",
        pravilo: (p0: unknown) => `правило${p0}`,
        isklyuchenie: "исключение",
        isklyuchenie2: (p0: unknown) => `исключение ${p0}`,
        zagruzka: "Загрузка…",
        obschieZapisiS: (p0: unknown) => `Общие записи с: ${p0}. `,
        sovpavsheeZaberetOnoVyshe: (p0: unknown) => `Совпавшее заберёт «${p0}» — оно выше.`,
        sovpavsheeZaberetEtoPravilo: "Совпавшее заберёт это правило — оно выше.",
        napryamuyu: "Напрямую",
        neNayden: (p0: unknown) => `${p0} — не найден`,
        podnyatPrioritet: "Поднять приоритет",
        sbrostePoiskDlyaIzmeneniya: "Сбросьте поиск для изменения порядка",
        opustitPrioritet: "Опустить приоритет",
        izmenitPravilo: "Изменить правило",
        udalitPravilo: "Удалить правило",
        novoePravilo: " Новое правило",
        isklyuchenie3: "Исключение",
        sverhuVnizPobezhdaet: "Сверху вниз — побеждает",
        adresDostaetsyaSamomuVerhnemu: "Адрес достаётся самому верхнему правилу, которое его назвало; остальное идёт напрямую. Порядок меняется стрелками.",
        pervoeSovpadenie: "первое совпадение",
        izmeneniyaSohranyayutsyaSamiPravilo: ". Изменения сохраняются сами. Правило «Напрямую» выше туннельных — это исключение: выбранное пойдёт мимо VPN.",
        poiskPravilPoNazvaniyu: "Поиск правил по названию, сервису или выходу…",
        ochistitStrokuPoiska: "Очистить строку поиска",
        naydeno: "найдено ",
        iz: " из ",
        pravilNetVesTrafik: "Правил нет — весь трафик идёт напрямую.",
        dobavtePravilaDlyaServisov: "Добавьте правила для сервисов (YouTube, Telegram, Discord...) или направьте нужный трафик через VPN.",
        nastroitVyhodVpn: "Настроить выход VPN",
        poZaprosu: "По запросу «",
        nichegoNeNashlos: "» ничего не нашлось.",
        sbrositPoisk: "Сбросить поиск",
        dlya: "для ",
        vyklyucheno: " · выключено",
        vyklyuchitPravilo: (p0: unknown) => `Выключить правило ${p0}`,
        vklyuchitPravilo: (p0: unknown) => `Включить правило ${p0}`,
    },
    sections: {
        glavnaya: "Главная",
        pravila: "Правила",
        diagnostika: "Диагностика",
        nastroyki: "Настройки",
    },
    selfUpdateCard: {
        obnovitDo: "Обновить до",
        pereustanovit: "Переустановить",
        vyberiteVersiyu: "Выберите версию",
        neUstanovilos: "не установилось",
        interfeysObnovlen: "Интерфейс обновлён",
        perezagruziteStranitsu: "Перезагрузите страницу.",
        interfeys: "Интерфейс",
        seychas: "Сейчас",
        posleUstanovkiPerezagruziteStranitsu: "После установки перезагрузите страницу.",
        versiyaInterfeysa: "Версия интерфейса",
        zagruzka: "загрузка…",
        relizovNeNaydeno: "релизов не найдено",
        svezhaya: "свежая",
        spisokVersiyNePrishel: "Список версий не пришёл — проверьте интернет на роутере. Можно поставить пакет вручную:",
        gitlabComXyzmeanSplify2: "gitlab.com/xyzmean/splify2 (ветка dist)",
        ustanovschikSkazal: "Установщик сказал",
    },
    settings: {
        diagnostika: "Диагностика",
        obschee: "Общее",
        katalog: "Каталог",
        dopolnitelno: "Дополнительно",
        oPo: "О ПО",
        nastroyki: "Настройки",
        proverokSOtkazom: (p0: unknown) => `проверок с отказом: ${p0}`,
        proverokSPreduprezhdeniem: (p0: unknown) => `проверок с предупреждением: ${p0}`,
        nahodokNet: "находок нет",
        spiskovIspolzuetsya: (p0: unknown) => `списков используется: ${p0}`,
        svoihSpiskov: (p0: unknown) => `своих списков: ${p0}`,
    },
    specv2: {
        porty: (p0: unknown) => `${p0} (порты)`,
        porty2: (p0: unknown, p1: unknown) => `${p0} (порты ${p1})`,
    },
    telemetryCard: {
        modelRouteraIVersiya: "модель роутера и версия OpenWrt, версии splify2 и ядра, страна, город и ",
        nomerAvtonomnoySistemyVidy: "номер автономной системы, виды выходов и то, подняты ли они, номера списков каталога, ",
        domenPaneliPodpiskiTolko: "домен панели подписки — только две последние метки, ",
        nomeraSrabotavshihProverokI: "номера сработавших проверок и счётчики событий с загрузки; при падении ядра ",
        iliTunnelyaChtoImenno: "или туннеля — что именно упало, причина из закрытого набора, код возврата и сигнал ",
        iSkolkoRazEto: "и сколько раз это было с загрузки.",
        niOdnogoIpAdresa: "ни одного IP-адреса, ссылок подписок и токенов в них, названий подписок, ",
        imenUzlovIIh: "имён узлов и их адресов, имён выходов и правил, имён своих списков, ключей туннелей, ",
        schetchikovTrafikaIChisla: "счётчиков трафика и числа устройств в сети; ни одной строки журнала и ни одного текста ",
        oshibkiVTomChisle: "ошибки — в том числе в отчёте о падении, где от журнала уезжает только сам факт.",
        neSohranilos: "не сохранилось",
        otchetSnovaBudetUezzhat: "Отчёт снова будет уезжать раз в час",
        otpravkaVyklyuchena: "Отправка выключена",
        paketNeSobralsya: "пакет не собрался",
        otchetORabote: "Отчёт о работе",
        otpravlyatOtchetORabote: "Отправлять отчёт о работе раз в час",
        otchetORaboteUezzhaet: "Отчёт о работе уезжает раз в час, а при падении ядра, обхода DPI или туннеля — сразу. Он включён по умолчанию; выключить можно здесь.",
        nichegoNeOtpravlyaetsya: "Ничего не отправляется.",
        poslednyayaOtpravka: "Последняя отправка",
        eeEscheNeBylo: "её ещё не было",
        identifikator: "Идентификатор",
        proshlayaOtpravkaNeUdalas: "Прошлая отправка не удалась",
        uezzhaet: "Уезжает",
        neUezzhaet: "Не уезжает",
        vPaketeAdresaNet: "В пакете адреса нет. При самой отправке получатель видит адрес, как его видит любой сайт, и в базу он не пишется.",
        sobiraem: "Собираем…",
        pokazatPaket: "Показать пакет",
    },
    vlessPanel: {
        neSkachalos: "не скачалось",
        podpiskaZagruzhenaBayt: (p0: unknown) => `Подписка загружена: ${p0} байт`,
        nuzhnaSsylkaVidaHttps: "Нужна ссылка вида https://… на подписку либо одна или несколько ссылок vless:// или hysteria2:// ",
        cherezProbelSmeshivatEti: "через пробел. Смешивать эти две формы нельзя: роутер возьмёт только одну.",
        vstavteSsylkuNaPodpisku: "Вставьте ссылку на подписку или ссылку vless://.",
        pervyyRabochiy: "первый рабочий",
        uzel: (p0: unknown) => `узел ${p0}`,
        ssylkaNaPodpiskuIli: "Ссылка на подписку или vless://",
        httpsExampleComSub: "https://example.com/sub/xxxxx  —  или  vless://…",
        obnovit: " Обновить",
        zagruzit: " Загрузить",
        panelPodpiski: "Панель подписки: ",
        identifikatorEtogoRouteraDlya: "Идентификатор этого роутера для панели:",
        onPerezhivaetSbrosNastroek: "— он переживает сброс настроек. MAC роутера панели не отправляется.",
        faylNaRoutere: "Файл на роутере: ",
        bayt: " байт",
        obnovlen: (p0: unknown) => `, обновлён ${p0}`,
        uzlovPrigodno: " · узлов пригодно ",
        propuscheno: (p0: unknown) => `, пропущено ${p0}`,
        chuzhihProtokolov: (p0: unknown) => `, чужих протоколов ${p0}`,
        uzel2: "узел",
        uzlov: "узлов",
        naprimer: (p0: unknown) => `, например «${p0}»`,
        prochiePrichinyUzlov: "прочие причины — узлов ",
        podpiskiNetBezNee: "Подписки нет. Без неё выход никуда не ведёт: узлы ядро берёт только из файла.",
        sohraniteVyhodUzlyYadro: "Сохраните выход — узлы ядро покажет для уже сохранённой настройки.",
        uzlov2: "узлов ",
        vybran: " · выбран: ",
        ostanovitOstalos: (p0: unknown) => `Остановить (осталось ${p0})`,
        proveritVse: "Проверить все",
        pervyyRabochiy2: "Первый рабочий",
        neSlomaetsyaPriObnovlenii: "не сломается при обновлении подписки",
        uzel3: (p0: unknown) => `Узел ${p0}`,
        vOcheredi: "в очереди",
        idetProverka: "идёт проверка",
        otvet: "ответ ",
        ms: " мс",
        podklyuchenie: "подключение ",
        proveryaem: "Проверяем…",
        vOcheredi2: "В очереди",
        proverit: "Проверить",
    },
    vlessScreen: {
        nodesUsed: (n: number) => ` · локаций: ${n}`,
        vruchnuyu: "вручную",
        kazhdye30Minut: "каждые 30 минут",
        kazhdyyChas: "каждый час",
        kazhdye2Chasa: "каждые 2 часа",
        kazhdye3Chasa: "каждые 3 часа",
        kazhdye6Chasov: "каждые 6 часов",
        kazhdye12Chasov: "каждые 12 часов",
        razVSutki: "раз в сутки",
        razVDvoeSutok: "раз в двое суток",
        razVTroeSutok: "раз в трое суток",
        obnovitsyaPriBlizhaysheyProverke: "обновится при ближайшей проверке",
        sleduyuscheeCherezMin: (p0: unknown) => `следующее через ${p0} мин`,
        sleduyuscheeCherezCh: (p0: unknown) => `следующее через ${p0} ч`,
        sleduyuscheeCherezD: (p0: unknown) => `следующее через ${p0} д`,
        nuzhnaSsylkaPodpiskiHttp: "Нужна ссылка подписки (http:// или https://) либо ссылка vless:// или hysteria2://",
        imyaLatinitsaTsifryDefis: "Имя: латиница, цифры, дефис или подчёркивание",
        podpiskaNeSohranilas: "подписка не сохранилась",
        podpiskaSkachalasNoPrigodnyh: "Подписка скачалась, но пригодных узлов в ней нет",
        podpiskaNeSkachalas: "подписка не скачалась",
        podpiskaObnovilasNoPrigodnyh: "Подписка обновилась, но пригодных узлов в ней нет",
        neVyshloZadatObnovlenie: "не вышло задать обновление",
        podpiskaNeUdalilas: "подписка не удалилась",
        zagruzka: "Загрузка…",
        ssylkiVless: "ссылки vless://",
        obnovlena: "обновлена ",
        neSkachana: "не скачана",
        vzyataVyhodami: (p0: unknown, p1: unknown) => `взята выходами: ${p0}${p1}`,
        neIspolzuetsya: "не используется",
        obnovlyat: "Обновлять",
        obnovlyaem: "Обновляем…",
        obnovit: "Обновить",
        udalit: (p0: unknown) => `удалить ${p0}`,
        udalyaem: "Удаляем…",
        udalit2: "Удалить",
        dobavitPodpisku: "Добавить подписку",
        imyaNeobyazatelno: "имя (необязательно)",
        imyaPodpiski: "имя подписки",
        ssylkaPodpiskiIliVless: "ссылка подписки или vless://",
        ssylkaPodpiski: "ссылка подписки",
        dobavlyaem: "Добавляем…",
        dobavit: "Добавить",
    },
    vpn: {
        subscriptions: (n: number) => plural(n, 'подписка', 'подписки', 'подписок'),
        locations: (n: number) => plural(n, 'локация', 'локации', 'локаций'),
        svoiTunneli: "Свои туннели",
        vzyaty: (p0: unknown) => `взяты: ${p0}`,
        wireguardAmneziawgOpenvpnNi: "WireGuard, AmneziaWG, OpenVPN — ни один не взят",
        vzyaty2: (p0: unknown, p1: unknown) => `взяты: ${p0} · ${p1}`,
        niOdnaPodpiskaNe: "ни одна подписка не взята выходом",
        interfeysovNet: "интерфейсов нет",
    },
    xsteerPanel: {
        yes: "есть",
        no: "нет",
        neBylo: "не было",
        sNazad: (p0: unknown) => `${p0} с назад`,
        minNazad: (p0: unknown) => `${p0} мин назад`,
        chNazad: (p0: unknown) => `${p0} ч назад`,
        neizvestno: "неизвестно",
        yadroNeSoobschaetSborka: "Ядро не сообщает — сборка старее 1.5.0.",
        vyklyuchena: "выключена",
        razgruzkaNeVklyuchilasUstroystvo: "Разгрузка не включилась: устройство или ядро Linux её не поддерживают, либо она выключена в настройке интерфейса. Туннель работает, но заметно медленнее.",
        polnaya: "полная",
        razgruzkaVstalaTselikomTunnel: "Разгрузка встала целиком — туннель идёт на полной скорости.",
        chastichnaya: "частичная",
        vstalaNeTselikomOtdacha: (p0: unknown, p1: unknown) => `Встала не целиком: отдача ${p0}, приём склеенного ${p1}. Половина прибавки к скорости потеряна.`,
        routerNeOtdalSsylku: "роутер не отдал ссылку",
        routerNeOtvetil: "роутер не ответил",
        prinyataHabInterfeysPodnimaetsya: (p0: unknown) => `принята: хаб ${p0}. Интерфейс поднимается заново.`,
        ssylkaNePrinyata: "ссылка не принята",
        brauzerNeDalDostup: "браузер не дал доступ к буферу — выделите строку руками",
        zagruzka: "Загрузка…",
        routerNeRasskazyvaetPro: "Роутер не рассказывает про xsteer",
        ustanovlennyySplify2SostoyanieTunneley: "Установленный splify2 состояние туннелей не отдаёт — обновите splify2. Сами туннели работают.",
        interfeysovXsteerNet: "Интерфейсов xsteer нет",
        tunnelSozdaetsyaKakObychnyy: "Туннель создаётся как обычный интерфейс: зона фаервола, адрес и MTU ему нужны так же, как остальным. Ссылку ",
        mozhnoVstavitPryamoNa: " можно вставить прямо на странице создания — поля заполнятся сами.",
        sozdatVNastroykahSeti: "Создать в настройках сети",
        nastroit: "Настроить",
        tunnelNePodnimalsyaV: "Туннель не поднимался в эту загрузку: интерфейс выключен или ядро его ещё не запускало. Настройка при этом есть — состояния нет.",
        protsessNeOtvechaet: "Процесс не отвечает ",
        sChislaNizhePoslednie: " с — числа ниже последние, а не текущие.",
        hab: "хаб",
        rukopozhatie: "рукопожатие",
        razgruzka: "разгрузка",
        podtverzhdeno: "— подтверждено ",
        soedineniy: "соединений",
        potokTcp: "поток TCP",
        poddelnyyTcp: "поддельный TCP",
        skolkoRazPodnyatoeSoedinenie: "Сколько раз поднятое соединение падало за жизнь процесса. Восстановление происходит само и за секунды: туннель выглядит работающим и тогда, когда его чинят каждую минуту.",
        perepodnyatiy: "переподнятий",
        proshlo: "прошло",
        otbrosheno: "· отброшено ",
        vVyhode: "в выходе",
        ustroystvo: "Устройство ",
        opuschenoAdresaIZony: " опущено: адреса и зоны фаервола у него сейчас нет.",
        zdesPrivatnyyKlyuchEtogo: "Здесь приватный ключ этого пира — ссылка и есть доступ целиком. Не пересылайте её открытым каналом.",
        skopirovano: "Скопировано",
        kopirovat: "Копировать",
        pokazatSsylkuXs: "Показать ссылку xs://",
        vstavitDruguyuSsylku: "Вставить другую ссылку",
        zamenitNastroykuEtogoInterfeysa: "Заменит настройку этого интерфейса целиком — ключ, адрес и хаб — и поднимет его заново. Зона фаервола и имя устройства останутся.",
        xsKlyuch2030: "xs://<ключ>@203.0.113.7:443?pk=<ключ хаба>&ip=10.77.0.2/24",
        prinyatIPodnyatZanovo: "Принять и поднять заново",
        ssylki: "Ссылки ",
        nuzhnoRabotayuscheeYadro: " — нужно работающее ядро steer 2.0 или новее.",
    },
}
